# Generated by Django 4.2.6 on 2023-10-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
