# Generated by Django 4.2.6 on 2023-11-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction', models.CharField(max_length=200)),
                ('drug1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_drug1', to='drug.detail')),
                ('drug2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_drug2', to='drug.detail')),
            ],
        ),
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
