# Generated by Django 4.2.6 on 2023-11-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_detail_interaction_delete_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='name2',
            field=models.CharField(max_length=30),
        ),
    ]
